### ISSUE TITLE
sacad_r: ID3 tags like TPE1 or TALB are ignored

### ISSUE THREAD

**Issue by kriswebdev** [desbma/sacad#11]
sacad_r is unable to properly read the Artist or Album from some (all?) MP3 ID3 tags.

The issue lies in `sources/recurse.py`:
```
def get_metadata(audio_filepaths):
  """ Return a tuple of album, artist from a list of audio files. """
  artist, album = None, None
  for audio_filepath in audio_filepaths:
    mf = mutagen.File(audio_filepath)
    if mf is None:
      continue
    artist = mf.get("albumartist",
                    mf.get("artist", None))
    if artist is not None:
      artist = artist[0]
    album = mf.get("_album",
                   mf.get("album",
                          None))
    if album is not None:
      album = album[0]
    if artist and album:
      # stop at the first file that succeeds (for performance)
      break
  return artist, album
```
Mutagen get() lines should be:
```
    artist = mf.get("albumartist") or mf.get("artist") or mf.get("TPE1")
    album = mf.get("_album") or mf.get("album") or mf.get("TALB") # or mf.get("TIT2") for title
```

Some suggestions not related to this bug:

- A debug mode would be nice. There's no clue about error causes.
- For single-file folders where the album search fails, a title search `mf.get("TIT2")` would be a nice improvement.
- The install instructions could be more clear for Ubuntu 16. Specifically, we need `sudo apt-get install python3 python3-pip`

Thanks for the good work. You project should be more popular.

**Comment by desbma** [comment]
Thanks for the report, the ID3 handling should be now fixed.

I will address your other remarks soon.

**Comment by desbma** [comment]
> Some suggestions not related to this bug:
> 
> - A debug mode would be nice. There's no clue about error causes.

You are absolutely right, the `sacad` tool has a complex and verbose logging system, but it is not used by `sacad_r`. I need to find a way to display both visual progress and errors.

> - For single-file folders where the album search fails, a title search `mf.get("TIT2")` would be a nice improvement.

I'd recommend fixing your tags in that case. I don't want to introduce workarounds in SACAD, that may silently download unrelated covers if some files are incorrectly tagged.

> - The install instructions could be more clear for Ubuntu 16. Specifically, we need `sudo apt-get install python3 python3-pip`

It is not recommended to install PIP with Ubuntu's package manager, because PIP is updated very often and you will be stuck with an old version, that may break and be unsupported by the PIP maintainers (although the delta is low now because 16.04 is still young).
