### ISSUE TITLE
How does sacad_r recognize already existing cover files?

### ISSUE THREAD

**Issue by Kafkalasch** [desbma/sacad#12]
Hello,

how exactly does sacad_r recognize already existing cover art files?
When analizing my music library it says, that it says:
[... albums=316, missing covers=316, ...]

I already have several cover art files in my library which are automatically found by different music players.

My library is sorted like this: artist/album/song.flac and artist/album/someArbitraryName.jpg

Nevertheless, hhanks for your great work on this project

**Comment by desbma** [comment]
Hello,

`sacad_r` uses the filename you give it to find and download covers.

For example `sacad_r /my/music/dir 600 cover.jpg` will recursively search directories that have audio files but no `cover.jpg` file, and then search and download a cover and save it to that file.

As a special case, using the `+` sign instead of a filename will look for embedded cover and search/download/embed it if it is missing.

Unfortunately if your covers do not have a static filename, `sacad_r` will not handle that use case well.

Also if you use `sacad_r` with a lot of albums, please note that I am currently rewriting parts of the code to make it **a whole lot** faster, and will release a new version very soon (probably tomorrow)

**Comment by Kafkalasch** [comment]
Thanks for the fast reply.

Ok, I see.

Something different:
I do not know if this is relevant to you as I have never published something with pip but I see that you are very actively developing and resolving all issues, so maybe this could be of relevance: When trying to install sacad with pip on raspbian (jessie) it just ends with some unspecific error messages (at least at the first sight).

It turned out to be a problem with one of it's dependencies, namely Pillow. It was not able to build it without libjpeg8-dev. Maybe this is out of your control and something for the pillow-team. I just wanted you to know, in case someone else runs into troubles with installing on a raspberry pi.

**Comment by desbma** [comment]
Yes this is expected, although not very user friendly.

SACAD needs the Pillow library as a dependency which has parts written in C that need [some external libraries to build](http://pillow.readthedocs.io/en/3.0.x/installation.html#external-libraries).
