### ISSUE TITLE
Is it possible to specify source?

### ISSUE THREAD

**Issue by baoshan** [desbma/sacad#2]
```
Got 0 relevant (0 excluded) results from source 'CoverLibCoverSource'
Got 1 relevant (3 excluded) results from source 'AmazonCdCoverSource'
Got 1 relevant (0 excluded) results from source 'AmazonDigitalCoverSource'
Got 14 relevant (6 excluded) results from source 'GoogleImagesWebScrapeCoverSource'
```
I guess the current behavior  is choose `AmazonCdCoverSource` and ignore `AmazonDigitalCoverSource`.

Is it possible to have a chance to look at covers from  `AmazonDigitalCoverSource` or `GoogleImagesWebScrapeCoverSource`?

Thanks.

**Comment by desbma** [comment]
The algorithm does not favour Amazon CD results over Amazon Digital results. The choice of the cover to download is a lot more complicated than that and takes into account several factors (currently 10), you can see the code and it's description [here](https://github.com/desbma/sacad/blob/0688b926088d1c1b734bf5cb1df45ec65f471872/sacad/cover.py#L361).

SACAD is fully automated by design, so there is no way to manually search for only one source.
Hewever:
* You can disable "low quality" sources with the `-d` / `--disable-low-quality-sources` parameter. Currently it only disables Google Images.
* If you are curious about the results of a particular source, you can run SACAD with `-v debug`, and check the URL of the pages SACAD is internally parsing

If you find an example of query where you think SACAD makes the wrong choice, I'll be happy to look at it.

**Comment by baoshan** [comment]
I think the winner algorithm is well enough. I'll report here again if a real issue arises.
