### ISSUE TITLE
last.fm queries containing special characters fail.

### ISSUE THREAD

**Issue by lhupitr** [desbma/sacad#21]
Certain characters seem to trip up the last.fm query (&,'," ) and return 400 Bad Request errors:

2018-09-28 20:41:01,435 WARNING [LastFmCoverSource] Search with source 'LastFmCoverSource' failed: ClientResponseError 400, message='Bad Request'

Even copying album and artist names with these characters directly from last.fm to insert into the query will consistently produce this error.

**Comment by desbma** [comment]
Which version of sacad are you using?
Can you post an example of command?

**Comment by desbma** [comment]
That command works fine here, although LastFM does not return any results, it does not return any error either.

[Since version 2.1.6, punctuations is removed from queries anyway](https://github.com/desbma/sacad/commit/fb14c5a188261aec60f5b59f74626c98a0780fd7).

Also although this is quite an unusual convention, the LastFM API returns a 400 error when it does not recognize and artist/album couple, so the "bad request" error is not necessarily worth worrying about.

**Comment by lhupitr** [comment]
That's weird - I'm just copying and pasting directly from last.fm - if I put any artist / album combination in that doesn't contain those characters it works, the only way I get that error (without fail over 25-30 albums) is with the aforementioned characters.

https://www.last.fm/music/Royal+City/Little+Heart%27s+Ease

here's another one:
sacad -v debug -d "Bonnie 'Prince' Billy" "Cursed Sleep" 192 "/tmp/cover.png"
https://www.last.fm/music/Bonnie+%27Prince%27+Billy/Cursed+Sleep

**Comment by desbma** [comment]
Well, it turns out sacad does not find some results on Last.fm **because** it removes punctuation.
https://www.last.fm/music/Royal+City/Little+Heart%27s+Ease
vs
https://www.last.fm/music/Royal+City/Little+Hearts+Ease

I'll investigate...

**Comment by desbma** [comment]
Should be fixed in https://github.com/desbma/sacad/commit/585a1b6a1d6d7503f7d4e2578c7a11ffce0ba886.

I will release 2.1.7 soon.
