### ISSUE TITLE
sacad_r assumes one album per directory?

### ISSUE THREAD

**Issue by jakkarth** [desbma/sacad#27]
Perhaps I've misunderstood something, but from what I can tell, sacad_r seems to be assuming that each album will be in its own directory. It's able to parse album names out of files, but the first album name it finds in a directory is where it stops looking, and all files in that directory get the same image even if they have different album names. Is there a flag I can pass or something that would tell sacad_r to use `distinct albumname` instead of `distinct dirname` to decide how to group files together to assign an image?

**Comment by desbma** [comment]
Yes it is correct that Sacad currently always assumes that an album is stored in a single directory.

I did that mostly for performance and because I think this covers most ways people organize their music library. Also many tools and players implicitly use the image file of each directory as the cover art.

I am open to changing this to make it more generic, but that opens a bunch of questions:
* performance of the library scan: if the typical album track count is 10-15, the scan will be 10-15x slower
* memory usage: the tags of all the files have to be kept in memory during the scan to be sure to find all files with the same (artist, album) couple and process them thereafter
* behaviour: 
  - where should the cover file be saved if files for an album are in different directories?
  - what should be the name of the cover file if a single directory contains files for several albums?

That would help if you describe how is you library organized (naming scheme). Do you a have several albums in a single directory, or are some albums spread in several directories?

**Comment by desbma** [comment]
So what I can do is:
* add an option to scan all files in each directory (with a warning that it will be slower)
* allow writing cover file with pattern (ie. "{artist}_{album}_cover.jpg") to cover the "non embedded" case

Would that cover your use case?

**Comment by jakkarth** [comment]
I believe it would, yes! :D

**Comment by desbma** [comment]
Implemented via https://github.com/desbma/sacad/commit/42d554d8017c6541d06cb96734c2851c3498bfb7
