### ISSUE TITLE
Rate limit by Amazon

### ISSUE THREAD

**Issue by seitzbg** [desbma/sacad#39]
Is there a way around hitting the rate limit / Captcha ?

**Comment by desbma** [comment]
I have tried various things (random user agent, accepting cookies, random sleep delays...) and none of them are bulletproof, unfortunately...

**Comment by seitzbg** [comment]
Aww I was gonna suggest random sleep... drat!  Thanks!

**Comment by desbma** [comment]
I have just increase the sleep delay (minimum 2 seconds between requests + 0 to 3 seconds of random delay), in case it helps...

**Comment by maszaa** [comment]
Using proxies could help. But finding a reliable free proxy is difficult.

**Comment by desbma** [comment]
For the first time in a long time, the automated tests have all passed : https://travis-ci.org/github/desbma/sacad/builds/689695805 so that must have helped a bit.

Once you get a captcha, I have noticed that you need to wait a long time (24h?) so that they "forget" your IP and send you the real pages.
