### ISSUE TITLE
SACAD as importable module?

### ISSUE THREAD

**Issue by keethesh** [desbma/sacad#42]
Is there a way to use SACAD as a module (or at least have a documentation on how to do it if it's already possible)? The only way I can use it in my current script is by generating a random filename, using os.system to run SACAD, and output it to that filename, then loading the file for whatever I need to do. Thanks!

**Comment by desbma** [comment]
There is no real "official" Python module level API, mostly because I didn't give it much though and don't know if anybody really cares.

However you can either:
* use a process invocation (using the `subprocess` is much better than `os.system` though)
* call `sacad.search_and_download` like here: https://github.com/desbma/sacad/blob/c102875550fa3af8bc4d27db343b12b00934fabb/sacad/__init__.py#L167-L181

**Comment by keethesh** [comment]
Thanks, I'll try doing that! Can I modify SACAD to make it importable?

**Comment by desbma** [comment]
It is already importable. `sacad_r` uses the `sacad` module.
