### ISSUE TITLE
Feature: switch to disable Amazon sources

### ISSUE THREAD

**Issue by maszaa** [desbma/sacad#53]
I get pictures of pill bottles etc. with domestic music...

**Comment by desbma** [comment]
Do you have an example of query which leads to wrong results?

**Comment by maszaa** [comment]
Try "Sakari Kuosmanen: Suuri onni" for example. Artist: Sakari Kuosmanen, Album: Suuri onni.

**Comment by maszaa** [comment]
Artist: Tuomari Nurmio & Viides Kolonna
Album: Maailmanpyörä palaa

**Comment by desbma** [comment]
The problem for this query is that [this page from Amazon](https://www.amazon.com/s?k=tuomari+nurmio+viides+kolonna+maailmanpyora+palaa&i=digital-music&s=relevancerank) has no results, but shows instead completely unrelated products.

LastFM returns the good results, but with a low resolution, Sacad then compares the LastFM reference to the unrelated Amazon results and correctly identifies that are not matching but since you have requested a high resolution and it has no better result, it downloads a bad Amazon image.

If you increase the size tolerance, (for example with `-t 50` wich allows 50% of difference with what you have requested, so for 600px you can get down to 300px covers) the good LastFM result is no longer excluded, and it will be favored over the Amazon bad ones.

**Comment by maszaa** [comment]
I created an own fork to set Amazon sources as low quality. Does the trick for me because I rather search the cover myself than get irrelevant or small covers. I have a cron job setup so that if no covers are found it will email me about that.

But I think it could be a good feature to let the user select which sources should be used. For example `--sources deezer,lastfm`

**Comment by maszaa** [comment]
Would it be possible to ignore Amazon search results if the page crawled has

> Showing results from All Departments
> No results for <artist> <album> in Digital Music

**Comment by bashl** [comment]
I got a similar result, when it fails to acquired an image of amazon it goes to whatever thing it got. See the example:  "AlbumCover.jpg" is the desired filename of sacad and "cover.jpg" is the album cover I already had.
