### ISSUE TITLE
Script downloads random product images

### ISSUE THREAD

**Issue by Stooovie** [desbma/sacad#65]
`sacad_r /Volumes/Public/iTunes\ Media/Music 600 cover.jpg  ` used to add missing covers to my music collection downloaded mostly utter nonsense - random product images (seemingly totally unrelated) from Amazon. For example, it downloaded this for a Deep Purple album.
![cover](https://user-images.githubusercontent.com/10572373/140877481-8e2a0bed-35fc-492c-abc7-6574edb890d8.jpg)
The album does have proper tags and[ is available on Amazon](https://www.amazon.com/Very-Best-Deep-Purple/dp/B00000G6TL)

Any clues? Thanks.

**Comment by desbma** [comment]
Some sources have a risk of returning unrelated images, Amazon is one of those.
This can happen if you request very large images, because Amazon sometimes has 1600x1600 images when other sources rarely do.
However in your example 600px is a common size, and Deep Purple is not an obscure band so I'm surprised it returns an unrelated image.

Can you upload a single file from the album, so I can look at it and try to find what went wrong?

**Comment by Stooovie** [comment]
Hi, [here's one](https://0x0.st/-5EL.mp3). There was probably around 12 % of these unrelated (and franky hilarious) mismatches. Like these :)
![IMG_0263](https://user-images.githubusercontent.com/10572373/141013638-8d2aa218-f421-4db2-9380-60f650c0c987.PNG)

Thanks!

**Comment by desbma** [comment]
I also get unrelated result for a search of `Deep Purple` / `The Very Best of Deep Purple [EMI Single Disc]`.
But I get [the right cover](https://m.media-amazon.com/images/I/91UXPSlIJoL.jpg) for the album `The Very Best of Deep Purple`.

So my advice would be to carefully tag your files, especially for the artist / album tags. Stuff like year, edition, dist number etc. don't belong in the artist tag, there are dedicated tags for this.
