### ISSUE TITLE
GoogleImagesWebScrapeCoverSource doesn't seem to work anymore

### ISSUE THREAD

**Issue by moustachedelait** [desbma/sacad#70]
There's always zero results.

One of the issues seem to be the selector:
document.querySelectorAll('#search #rg_s .rg_di') is not returning any results on the page itself

document.querySelectorAll('.islir') does, but trying to put that in the code still doesn't seem to loop over any results.

**Comment by desbma** [comment]
I noticed that a while ago and failed to fix it at the time, but did not remove the source, because sometimes Google serves different page structures for different countries from the source IP, so I thought it might still work for some users.

I'll see if there is an easy way to update it, and remove it in the next version otherwise.

**Comment by wbtcpip2** [comment]
is there any update on this issue? any chance to have GoogleImagesWebScrapeCoverSource working n the near future?

**Comment by desbma** [comment]
Don't hold your breath, this is a hobby project for me, and this issue is low priority because Google Images generally returns low quality results anyway.

Of course pull requests to fix the Google source are welcome.

Also if Google is actively preventing scraping, which seems to be the case, this is a lost cause, and I will likely just remove the source.

**Comment by wbtcpip2** [comment]
thank you. i saw another pyton project around that use Apple Music as cover source. Do you think is it possible to add it to sacad as source in the future? it would be a very good replacement for the google source.

**Comment by desbma** [comment]
@wbtcpip2 

Please open a new issue, with link about said project.

**Comment by desbma** [comment]
Google Images source has been removed ace45fb
