### ISSUE TITLE
Package dependencies for people who install the package from source

### ISSUE THREAD

**Issue by hboetes** [desbma/sacad#73]
For some reason I prefer to install packages from source and this is the list of dependencies I came up with.

```
sudo dnf install python3-aiohttp python3-lxml optipng jpegoptim python3-cssselect python3-appdirs python3-bitarray python3-unidecode python3-pillow python3-mutagen python3-tqdm
```

Perhaps this is worth mentioning in the README. If not feel free to close this bug.

**Comment by desbma** [comment]
I think you mean "from distribution packages", because the dependencies for installation ["from source"](https://github.com/desbma/sacad#from-source) are listed in [`requirements.txt`](https://github.com/desbma/sacad/blob/master/requirements.txt), and are also what gets installed with `pip install sacad`.

I don't know which distribution and at which version you use and therefore I have not knowledge or control of the exact version of the dependencies this may pull, so they may be conflicts, crashes or untested configurations, and there is no way I can support this.

I only support Arch Linux because I maintain the [sacad AUR package](https://aur.archlinux.org/packages/sacad) and use it myself, so I can spot any regression/bug quickly. Outside of Arch Linux, I'd recommend staying with the pip method, with a venv if needed.
