### ISSUE TITLE
Probe larger amazon cover using undocumented cover image api

### ISSUE THREAD

**Issue by baoshan** [desbma/sacad#9]
Let's check a SACAD command:

`sacad -d -t 100 "Sergiu Celibidache" "Verdi: Requiem" 1600 cover.jpg`

It grabs you a `500 x 500` cover from `AmazonCD` source. I think the result can be improved using the following (undocumented) URL: `http://z-ecx.images-amazon.com/images/P/{REPLACE_WITH_ASIN}.09._SCRMZZZZZZ_.jpg`

Which provides [this](http://z-ecx.images-amazon.com/images/P/B00068V38E.09._SCRMZZZZZZ_.jpg) 

For some ASIN, that url will returns a `1x1` image, which should be ignored. This api is used by myself in some projects with satisfying result.

Could we probe the url to see if it can benefit?

**Comment by desbma** [comment]
Thanks for the tip.

Do you know if there is a way to know if the image is there without downloading it? I'd like to avoid doing another HTTP request for performance.
If you don't know, can you please provide an example that does not have this image, I'll try to compare and investigate.

**Comment by baoshan** [comment]
Sorry, I don't know if we can know that in prior.

Below ASINs have no bigger cover:

`B000003FCS`, `B0000026YX`,`B00008HCF1`

**Comment by desbma** [comment]
@baoshan how did you find out about the alternate URL since it does not seem to be used in Amazon pages?

**Comment by baoshan** [comment]
I learn it [here](https://sourceforge.net/p/xld/code/HEAD/tree/trunk/XLD/XLDCoverArtSearcher.m#l463). I guess it has been there for a while.

**Comment by desbma** [comment]
The search you refer to gets from Amazon only one result with ASIN B014I6G1IG (which does NOT have bigger image).

If you search on amazon.co.uk (with `-a co.uk`), you get result with B00068V38E (which has bigger image, same as in your example).
It turns out I was using another method to build the URL, but if you run:
`sacad -d -t 100 "Sergiu Celibidache" "Verdi: Requiem" 1600 /tmp/cover.jpg -a co.uk`
It will lead to the same exact image (with different URL): http://ecx.images-amazon.com/images/I/81lTi7Z2hJL._SL1300_.jpg
